# Generated by Django 2.1 on 2018-08-21 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SuperSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SuperSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substore', models.CharField(max_length=120)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_name', models.CharField(max_length=120)),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarkets.SuperSize')),
                ('superstore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarkets.SuperName')),
            ],
        ),
    ]
