# Generated by Django 2.1 on 2018-08-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersub',
            name='lat',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
        migrations.AlterField(
            model_name='supersub',
            name='lon',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
    ]
